### ISSUE TITLE
Convert from MIL-STD-2525C to MIL-STD-2525D

### ISSUE THREAD

**Issue by simonhuwiler** [spatialillusions/mil-std-2525#7]
Hello there!

I am lookin for a way to convert MIL-STD-2525C to MIL-STD-2525D. I wonder if this could be done based on your libraries. What do you think?

Thank you very much!

**Comment by spatialillusions** [comment]
You can’t do that with my code unfortunately, but there is an excel chart that DoD can provide to do that. Please send me an email if you want more information. 

/Måns

**Comment by simonhuwiler** [comment]
Thank you Måns, the problem has solved itself :)
